### ISSUE TITLE
Cant create new ads

### ISSUE THREAD

**Issue by jniggemann** [donwayo/ebayKleinanzeigen#35]
This is probably due to the shipping options that are default. My ads are all "PICKUP", but this is not set (or the code doesn't get there):
![img](https://user-images.githubusercontent.com/1318059/140602400-362b9ea9-845e-4014-bd88-f9c6e3527d56.png)
```

Traceback (most recent call last):
  File "/home/jn/bin/ebayKleinanzeigen/kleinanzeigen.py", line 564, in <module>
    fPosted = post_ad(driver, ad, True)
  File "/home/jn/bin/ebayKleinanzeigen/kleinanzeigen.py", line 317, in post_ad
    shipment_select.select_by_visible_text("Nur Abholung")
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/select.py", line 120, in select_by_visible_text
    self._setSelected(opt)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/select.py", line 212, in _setSelected
    option.click()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: Element is not currently visible and may not be manipulated
  (Session info: chrome=90.0.4430.212)
```

**Comment by DreckSoft** [comment]
Yes, pickup does not work anymore. Shipping is OK.

**Comment by jniggemann** [comment]
> Yes, pickup does not work anymore. Shipping is OK.

For me it's the other way round, pickup _does_ work and shipping does not.

**Comment by zapp42** [comment]
[0007-Make-PICKUP-shipping-type-work-again.txt](https://github.com/donwayo/ebayKleinanzeigen/files/7577352/0007-Make-PICKUP-shipping-type-work-again.txt)

Try this.

**Comment by Airwave1981** [comment]
> [0007-Make-PICKUP-shipping-type-work-again.txt](https://github.com/donwayo/ebayKleinanzeigen/files/7577352/0007-Make-PICKUP-shipping-type-work-again.txt)
> 
> Try this.

Thanks, but raises: 

**name 'shipment_select' is not defined**

**Comment by kahironimashte** [comment]
How can I apply all those changes? Donwayo seems to be busy in real life for some time now ;-)

**Comment by jniggemann** [comment]
I'm using @Airwave1981's [fork](https://github.com/Airwave1981/ebayKleinanzeigen) which works flawlessly for me when shipping = pickup.

**Comment by DreckSoft** [comment]
Unfortunately @Airwave1981 fork does ignore shipping type = PICKUP and sometimes even crash with SHIPPING.

Traceback (most recent call last):
  File "/home/admin/Development/ebayKleinanzeigen/./kleinanzeigen.py", line 579, in <module>
    fPosted = post_ad(driver, ad, True)
  File "/home/admin/Development/ebayKleinanzeigen/./kleinanzeigen.py", line 438, in post_ad
    submit_button.click()
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=96.0.4664.45)

**Comment by Airwave1981** [comment]
> Unfortunately @Airwave1981 fork does ignore shipping type = PICKUP and sometimes even crash with SHIPPING.
> 
> Traceback (most recent call last): File "/home/admin/Development/ebayKleinanzeigen/./kleinanzeigen.py", line 579, in fPosted = post_ad(driver, ad, True) File "/home/admin/Development/ebayKleinanzeigen/./kleinanzeigen.py", line 438, in post_ad submit_button.click() File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click self._execute(Command.CLICK_ELEMENT) File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute return self._parent.execute(command, params) File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute self.error_handler.check_response(response) File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable (Session info: chrome=96.0.4664.45)

Is there a fix out already I can directly implement?
Thx

**Comment by DreckSoft** [comment]
I don't think so. I tried to research what the exact issue is but I didn't succeed. Strangely the crash with SHIPPING only happens on one ad with me. But PICKUP gets ignores with add ads. The original one always (?) crashes on PICKUP.

**Comment by kahironimashte** [comment]
I cloned the fork of @Airwave1981 and it works for the most part :-) All offers are set to shipping possible even if they are only for pickup. But it's working again, yay.

**Comment by Schmuuu** [comment]
Hi guys,
I just found and tried this python script and failed to create an Ad for PICKUP.
I noticed this issue and that there wasn't a fix yet (at least not mentioned here). 
Trying to post my ad in any way I already implemented a few fixes; like these: 
- https://github.com/donwayo/ebayKleinanzeigen/issues/35#issuecomment-974918073
- https://github.com/donwayo/ebayKleinanzeigen/issues/33#issuecomment-945116405

I came farther, but price type "FIXED" and PICKUP were still not selected and the ad creation failed.
I noticed price type is (now) a drop down and wasn't handled as such and for PICKUP the xpath changed.

So I made some code changes and got it working for me. 

At least for PICKUP the ad was successfully created. For SHIPPING additional changes may be required (I haven't tested SHIPPING).

Hope it helps:
https://github.com/Schmuuu/ebayKleinanzeigen
